// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFvA7c5-Hz9bOk3HBCmBWbX2UlaTL8nFo',
    appId: '1:722178177690:web:d56df8e7b516e29aa6bd23',
    messagingSenderId: '722178177690',
    projectId: 'quick-ledger-app',
    authDomain: 'quick-ledger-app.firebaseapp.com',
    storageBucket: 'quick-ledger-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArYb0liuHdJRd6U_rvRQnhGtlMoin4GD8',
    appId: '1:722178177690:android:bf54a80847bc0b3ea6bd23',
    messagingSenderId: '722178177690',
    projectId: 'quick-ledger-app',
    storageBucket: 'quick-ledger-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBmKUY3fD4T2XDJQXB0aONzP-uVbSDEcs',
    appId: '1:722178177690:ios:aa6701e3255fe7c9a6bd23',
    messagingSenderId: '722178177690',
    projectId: 'quick-ledger-app',
    storageBucket: 'quick-ledger-app.firebasestorage.app',
    iosBundleId: 'com.example.quickLedger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBmKUY3fD4T2XDJQXB0aONzP-uVbSDEcs',
    appId: '1:722178177690:ios:aa6701e3255fe7c9a6bd23',
    messagingSenderId: '722178177690',
    projectId: 'quick-ledger-app',
    storageBucket: 'quick-ledger-app.firebasestorage.app',
    iosBundleId: 'com.example.quickLedger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFvA7c5-Hz9bOk3HBCmBWbX2UlaTL8nFo',
    appId: '1:722178177690:web:077fddc81f53bb02a6bd23',
    messagingSenderId: '722178177690',
    projectId: 'quick-ledger-app',
    authDomain: 'quick-ledger-app.firebaseapp.com',
    storageBucket: 'quick-ledger-app.firebasestorage.app',
  );
}
